server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: boyu
    url: jdbc:postgresql://localhost:5433/serverdb
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true